package char

const (
	Space        = rune(' ')
	NewLine      = rune('\n')
	Return       = rune('\r')
	Tab          = rune('\t')
	Plus         = rune('+')
	Minus        = rune('-')
	Mul          = rune('*')
	Div          = rune('/')
	Mod          = rune('%')
	Equal        = rune('=')
	Exclaim      = rune('!')
	Tilde        = rune('~')
	Ampersand    = rune('&')
	Pipe         = rune('|')
	Carot        = rune('^')
	Dot          = rune('.')
	Comma        = rune(',')
	LeftParen    = rune('(')
	RightParen   = rune(')')
	LeftBrace    = rune('{')
	RightBrace   = rune('}')
	LeftBracket  = rune('[')
	RightBracket = rune(']')
	Colon        = rune(':')
	Semicolon    = rune(';')
	LessThan     = rune('<')
	GreaterThan  = rune('>')
	DoubleQuote  = rune('"')
	SingleQuote  = rune('\'')
	BackQuote    = rune('`')
	Hash         = rune('#')
	BackSlash    = rune('\\')
	At           = rune('@')
	Underscore   = rune('_')
)
